image:
  debug: true
replicaCount: 1
autoCreateTopicsEnable: true
logRetentionHours: 1
logSegmentBytes: _1073741824
logRetentionCheckIntervalMs: 300000
maxMessageBytes: _20971520
externalAccess:
  enabled: false
  autoDiscovery:
    enabled: true
kraft:
  enabled: false
extraEnvVars:
  - name: KAFKA_ENABLE_KRAFT
    value: "false"
  - name: KAFKA_CFG_DELETE_TOPIC_ENABLE
    value: "true"  # Add this line to enable topic deletion
  - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
    value: "true"  # Add this line to enable topic auto-creation
zookeeper:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: false
    size: 2Gi
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
